PEPERCLIP_HASH = ENV['PEPERECLIP_HASH']

HOST_URL = ENV.fetch('HOST_URL', 'http://192.168.1.69:3000')

IONIC_API_KEY = ENV['IONIC_API_KEY']
IONIC_SECURITY_PROFILE = ENV['IONIC_SECURITY_PROFILE']

GCM_API_KEY = ENV['GCM_API_KEY']

SIDEKIQ_USERNAME = ENV.fetch('SIDEKIQ_USERNAME', 'sidekiqadmin')
SIDEKIQ_PASSWORD = ENV.fetch('SIDEKIQ_PASSWORD', 'sidekiqpassword')

GA_ID = ENV.fetch('GA_ID', 'UA-93256916-1')
