# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12a8a6c8342160134802eff5e21b9fb222477cd0eb9f03864cf0aebfc69b04e73b87a88ccc97351e5190362bccb1d30467d2763e3e1cb92ceb785ec5cb8f0492

test:
  secret_key_base: 78d644f2a6e34820057b629cfd7e96f77351daf67f3dabd3fe9f8af84f372022511bd457b2e731bcbbaae076525914357bd4ee9c663a57b46d2d848b04af7eda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 63e52bfbea08ffb15abc767a4c9797e89102dfabea0f7817798ff49d7143cb0b34a5dfd91b8472da8fb89e2397c8102204e01522f52690726cac6a1212690711